### ISSUE TITLE
Problem with Evil VISUAL mode

### ISSUE THREAD

**Issue by juboba** [llemaitre19/jtsx#1]
When selecting text in Evil's VISUAL mode, instead of going to the matching bracket with `%` `point` is moved to the next line.

> Note: I report this issue here, because in any other mode this works fine. I suspect it might have to do with the definition of text objects (?).

To reproduce:
- Start VISUAL line mode: `V`
- Go to the end of the line: `$`
- Go to the matching bracket/parentheses/etc: `%`

### Expected result:
Selection goes to the matching bracket
![evil_line_problem3](https://github.com/llemaitre19/jtsx/assets/1189739/ad5a8bfb-8fa0-431f-992f-950182b7e31a)

Using `tsx-ts-mode` it works fine:
![evil_line_problem4](https://github.com/llemaitre19/jtsx/assets/1189739/120f633b-4083-4a4c-9329-abe7a92598f7)

### Actual result:
Selection goes to the next line

![evil_line_problem](https://github.com/llemaitre19/jtsx/assets/1189739/a63aac90-d2c1-4378-891e-4d1a279dea98)
![evil_line_problem2](https://github.com/llemaitre19/jtsx/assets/1189739/f688b444-2868-4dd9-bef7-4124c7717a64)

**Comment by llemaitre19** [comment]
Thanks for your detailed issue.

Unfortunately, I cannot reproduce the bug neither on Emacs 29.1 nor on Emacs master branch. Maybe I am missing something.

> I suspect it might have to do with the definition of text objects (?).

Sorry, I do not know what you mean by `text objects` ?

Under the hood, it seems that the function `forward-list` is called when jumping from balanced expressions in `evil-mode`. I have no idea where the problem comes from because `jtsx` major modes should not alter this function. 

Here are some questions, that may help to catch the problem:
* The first 2 gifs are recorded with `tsx-ts-mode` on the 2 last ones with `jtsx-tsx-mode` , am I right ?
* What's your Emacs version ?
* Are you sure that `jtsx-tsx-mode` and `tsx-ts-mode`  run with same minor modes when comparing their behaviours ?
* I am not familiar with `evil-mode`, but `s` key seems not to be bound by default, so I suppose that it calls `evil-end-of-line`, that's it ?

**Comment by juboba** [comment]
hi @llemaitre19 ! Thank you very much for taking the time to think about the problem.
- The first and last 2 gifs were recorded with `jtsx-tsx-mode`. The second one was recorded with `tsx-ts-mode` to show that the problem doesn't happen.
I'm not an elisp expert, but according to what I've seen it seems `jtsx` doesn't touch anything regarding this.
I know evil-mode has a [configuration to allow the cursor go past the last character](https://evil.readthedocs.io/en/latest/settings.html#elispobj-evil-move-beyond-eol), but I checked its value and its `nil`.
- My emacs version is `29.1`.
- I will check the minor modes available in each mode.
- I haven't used `s`, but `V`, `$` and `%`

**Comment by llemaitre19** [comment]
> The first and last 2 gifs were recorded with jtsx-tsx-mode. The second one was recorded with tsx-ts-mode to show that the problem doesn't happen.

Ok, so it is not clear for me what the first gif demonstrates ?  Is it a working example with `jtsx-tsx-mode` when not using `Visual mode` ?

> I haven't used s, but V, $ and %

Sorry, I read wrong the dollar sign.

If it is possible, can you share the part of your configuration file related to `jtsx` ?

**Comment by juboba** [comment]
@llemaitre19 I'm closing this since it doesn't happen in a the fresh configuration I'm working on. Thank you.
